version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: store
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "nicolasurbanos10@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - 5050:80
    depends_on:
      - postgres